spring:
  datasource:
    url: 'jdbc:h2:mem:crm'
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: false
  h2:
    console:
      enabled: true
jwt:
  secret: ruw9doanqRHQfsfSPS+uglAhi/Wd5Zpwg9knAd5UIQw=
  expiration: 360000
main:
  allow-bean-definition-overriding: true
logging:
  config: classpath:log4j2.xml